/*
 * 002LED_with_Button.c
 *
 *  Created on: Feb 21, 2024
 *      Author: Shaik
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f446xx_gpio_driver.h"

#define HIGH			1
#define LOW				0
#define BUTTON_PRESSED	LOW

void buttonDebouncedelay(void)
{
	for ( int i = 0;  i < 400000; ++i);
}

//Entry
int main(void)
{
	GPIOx_Handle_t gpioLed;
	GPIOx_Handle_t gpioButton;

	//LED Init
	gpioLed.pGPIOx = GPIOA;
	gpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	gpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	gpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_SPEED_HIGH;
	gpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	gpioLed.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_NO_PUPD;
	GPIO_PeripheralClkCtrl(GPIOA, ENABLE);
	GPIO_Inint(&gpioLed);

	//Button Init
	gpioButton.pGPIOx = GPIOC;
	gpioButton.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	gpioButton.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	gpioButton.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_SPEED_HIGH;
	GPIO_PeripheralClkCtrl(GPIOC, ENABLE);
	GPIO_Inint(&gpioButton);

	/* Loop forever */
	for(;;)
	{
		if(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == BUTTON_PRESSED)// BUtton is Active low
		{
			buttonDebouncedelay();
			GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);
		}
	}
}
